FROM alpine:3

LABEL author="James Nainggolan"
LABEL company="James Networks" website="http://www.jamesnetworks.com/"

RUN mkdir hello
RUN echo "Hello-Wolrd" > "hello/world.txt"

CMD cat "hello/world.txt"